[2024-02-22T01:33:08.482+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-21T00:00:00+00:00 [queued]>
[2024-02-22T01:33:08.487+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-21T00:00:00+00:00 [queued]>
[2024-02-22T01:33:08.487+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-22T01:33:08.495+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-21 00:00:00+00:00
[2024-02-22T01:33:08.498+0000] {standard_task_runner.py:60} INFO - Started process 52 to run task
[2024-02-22T01:33:08.500+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-21T00:00:00+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpvheppe57']
[2024-02-22T01:33:08.501+0000] {standard_task_runner.py:88} INFO - Job 280: Subtask get_mail
[2024-02-22T01:33:08.528+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-21T00:00:00+00:00 [running]> on host e104f71d2ce8
[2024-02-22T01:33:08.573+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-21T00:00:00+00:00'
[2024-02-22T01:33:11.889+0000] {ImapSmtp.py:839} INFO - IMAP search: 'gmail:'Message from RPA Python' after:15-12-2023'
[2024-02-22T01:33:15.500+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('attachments/test.txt')
[2024-02-22T01:33:15.501+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-22T01:33:15.501+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_email.py", line 25, in get_mails_content
    attachment = mail.save_attachment(message=m["Message"], target_folder="./attachments/", overwrite=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 1223, in save_attachment
    return self._save_attachment(message, target_folder, overwrite, prefix)
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 1247, in _save_attachment
    with open(filepath, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'attachments/test.txt'
[2024-02-22T01:33:15.518+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240221T000000, start_date=20240222T013308, end_date=20240222T013315
[2024-02-22T01:33:15.529+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 280 for task get_mail ([Errno 2] No such file or directory: 'attachments/test.txt'; 52)
[2024-02-22T01:33:15.542+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-22T01:33:15.551+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-22T03:48:40.890+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-21T00:00:00+00:00 [queued]>
[2024-02-22T03:48:40.895+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-21T00:00:00+00:00 [queued]>
[2024-02-22T03:48:40.896+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-22T03:48:40.903+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-21 00:00:00+00:00
[2024-02-22T03:48:40.907+0000] {standard_task_runner.py:60} INFO - Started process 347 to run task
[2024-02-22T03:48:40.909+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-21T00:00:00+00:00', '--job-id', '307', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpxhxtf6rs']
[2024-02-22T03:48:40.910+0000] {standard_task_runner.py:88} INFO - Job 307: Subtask get_mail
[2024-02-22T03:48:40.939+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-21T00:00:00+00:00 [running]> on host e849c64d3231
[2024-02-22T03:48:40.985+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-21T00:00:00+00:00'
[2024-02-22T03:48:44.239+0000] {ImapSmtp.py:839} INFO - IMAP search: 'gmail:'Message from RPA Python' after:15-12-2023'
[2024-02-22T03:48:49.063+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('attachments/test.txt')
[2024-02-22T03:48:49.065+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-22T03:48:49.066+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_email.py", line 30, in get_mails_content
    attachment = mail.save_attachment(message=m["Message"], target_folder="./attachments/", overwrite=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 1223, in save_attachment
    return self._save_attachment(message, target_folder, overwrite, prefix)
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 1247, in _save_attachment
    with open(filepath, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'attachments/test.txt'
[2024-02-22T03:48:49.093+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240221T000000, start_date=20240222T034840, end_date=20240222T034849
[2024-02-22T03:48:49.122+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 307 for task get_mail ([Errno 2] No such file or directory: 'attachments/test.txt'; 347)
[2024-02-22T03:48:49.153+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-22T03:48:49.167+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-22T03:55:24.353+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-21T00:00:00+00:00 [queued]>
[2024-02-22T03:55:24.362+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-21T00:00:00+00:00 [queued]>
[2024-02-22T03:55:24.362+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-22T03:55:24.375+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-21 00:00:00+00:00
[2024-02-22T03:55:24.382+0000] {standard_task_runner.py:60} INFO - Started process 459 to run task
[2024-02-22T03:55:24.385+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-21T00:00:00+00:00', '--job-id', '311', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpwt6mz346']
[2024-02-22T03:55:24.387+0000] {standard_task_runner.py:88} INFO - Job 311: Subtask get_mail
[2024-02-22T03:55:24.426+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-21T00:00:00+00:00 [running]> on host e849c64d3231
[2024-02-22T03:55:24.490+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-21T00:00:00+00:00'
[2024-02-22T03:55:28.014+0000] {ImapSmtp.py:839} INFO - IMAP search: 'gmail:'Message from RPA Python' after:15-12-2023'
[2024-02-22T03:55:31.707+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('attachments/test.txt')
[2024-02-22T03:55:31.707+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-22T03:55:31.707+0000] {logging_mixin.py:188} INFO - error when saving attachment
[2024-02-22T03:55:31.707+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('attachments/test.txt')
[2024-02-22T03:55:31.708+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-22T03:55:31.708+0000] {logging_mixin.py:188} INFO - error when saving attachment
[2024-02-22T03:55:31.708+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('attachments/test.txt')
[2024-02-22T03:55:31.708+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-22T03:55:31.708+0000] {logging_mixin.py:188} INFO - error when saving attachment
[2024-02-22T03:55:31.708+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('attachments/test.txt')
[2024-02-22T03:55:31.708+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-22T03:55:31.709+0000] {logging_mixin.py:188} INFO - error when saving attachment
[2024-02-22T03:55:31.709+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('attachments/test.txt')
[2024-02-22T03:55:31.709+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-22T03:55:31.709+0000] {logging_mixin.py:188} INFO - error when saving attachment
[2024-02-22T03:55:31.709+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('attachments/test.txt')
[2024-02-22T03:55:31.709+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-22T03:55:31.710+0000] {logging_mixin.py:188} INFO - error when saving attachment
[2024-02-22T03:55:31.710+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('attachments/test.txt')
[2024-02-22T03:55:31.710+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-22T03:55:31.710+0000] {logging_mixin.py:188} INFO - error when saving attachment
[2024-02-22T03:55:31.710+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('attachments/test.txt')
[2024-02-22T03:55:31.710+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-22T03:55:31.710+0000] {logging_mixin.py:188} INFO - error when saving attachment
[2024-02-22T03:55:31.710+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('attachments/test.txt')
[2024-02-22T03:55:31.710+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-22T03:55:31.711+0000] {logging_mixin.py:188} INFO - error when saving attachment
[2024-02-22T03:55:31.711+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('attachments/test.txt')
[2024-02-22T03:55:31.711+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-22T03:55:31.711+0000] {logging_mixin.py:188} INFO - error when saving attachment
[2024-02-22T03:55:32.635+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-22T03:55:32.679+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=extract_email, task_id=get_mail, execution_date=20240221T000000, start_date=20240222T035524, end_date=20240222T035532
[2024-02-22T03:55:32.724+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-22T03:55:32.751+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
