[2024-02-21T08:06:15.393+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-24T01:00:00+00:00 [queued]>
[2024-02-21T08:06:15.412+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-24T01:00:00+00:00 [queued]>
[2024-02-21T08:06:15.413+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:06:15.433+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-01-24 01:00:00+00:00
[2024-02-21T08:06:15.441+0000] {standard_task_runner.py:60} INFO - Started process 137 to run task
[2024-02-21T08:06:15.444+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-01-24T01:00:00+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpcvo5mzko']
[2024-02-21T08:06:15.446+0000] {standard_task_runner.py:88} INFO - Job 173: Subtask get_mail
[2024-02-21T08:06:15.498+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-01-24T01:00:00+00:00 [running]> on host 96f19b77385b
[2024-02-21T08:06:15.578+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-01-24T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-24T01:00:00+00:00'
[2024-02-21T08:06:18.344+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_email.py", line 16, in get_mail
    mail.authorize(account=os.getenv("GMAIL_ACCOUNT"), password=os.getenv("GMAIL_PASSWORD"))
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 496, in authorize
    self.authorize_imap(
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 453, in authorize_imap
    self.imap_conn.login(account, password)
  File "/usr/local/lib/python3.8/imaplib.py", line 603, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Too many simultaneous connections. (Failure)'
[2024-02-21T08:06:18.371+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240124T010000, start_date=20240221T080615, end_date=20240221T080618
[2024-02-21T08:06:18.409+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 173 for task get_mail (b'[ALERT] Too many simultaneous connections. (Failure)'; 137)
[2024-02-21T08:06:18.428+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T08:06:18.445+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T08:12:41.958+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-24T01:00:00+00:00 [queued]>
[2024-02-21T08:12:41.968+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-24T01:00:00+00:00 [queued]>
[2024-02-21T08:12:41.969+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:12:41.987+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-01-24 01:00:00+00:00
[2024-02-21T08:12:41.994+0000] {standard_task_runner.py:60} INFO - Started process 128 to run task
[2024-02-21T08:12:41.996+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-01-24T01:00:00+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmp2um1jto9']
[2024-02-21T08:12:41.998+0000] {standard_task_runner.py:88} INFO - Job 205: Subtask get_mail
[2024-02-21T08:12:42.041+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-01-24T01:00:00+00:00 [running]> on host 968b17b6b013
[2024-02-21T08:12:42.105+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-01-24T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-24T01:00:00+00:00'
[2024-02-21T08:12:44.594+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_email.py", line 16, in get_mail
    mail.authorize(account=os.getenv("GMAIL_ACCOUNT"), password=os.getenv("GMAIL_PASSWORD"))
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 496, in authorize
    self.authorize_imap(
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 453, in authorize_imap
    self.imap_conn.login(account, password)
  File "/usr/local/lib/python3.8/imaplib.py", line 603, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Too many simultaneous connections. (Failure)'
[2024-02-21T08:12:44.607+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240124T010000, start_date=20240221T081241, end_date=20240221T081244
[2024-02-21T08:12:44.628+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 205 for task get_mail (b'[ALERT] Too many simultaneous connections. (Failure)'; 128)
[2024-02-21T08:12:44.659+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T08:12:44.705+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T08:17:44.449+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-24T01:00:00+00:00 [queued]>
[2024-02-21T08:17:44.458+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-24T01:00:00+00:00 [queued]>
[2024-02-21T08:17:44.458+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:17:44.476+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-01-24 01:00:00+00:00
[2024-02-21T08:17:44.484+0000] {standard_task_runner.py:60} INFO - Started process 82 to run task
[2024-02-21T08:17:44.488+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-01-24T01:00:00+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpw2m5ymc4']
[2024-02-21T08:17:44.492+0000] {standard_task_runner.py:88} INFO - Job 242: Subtask get_mail
[2024-02-21T08:17:44.536+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-01-24T01:00:00+00:00 [running]> on host 9f5f399fdbe3
[2024-02-21T08:17:44.596+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-01-24T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-24T01:00:00+00:00'
[2024-02-21T08:17:47.187+0000] {ImapSmtp.py:839} INFO - IMAP search: 'gmail:'Message from RPA Python' after:15-12-2023'
[2024-02-21T08:17:50.652+0000] {logging_mixin.py:188} INFO - Message from RPA Python0
[2024-02-21T08:17:50.659+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-147.txt')
[2024-02-21T08:17:50.660+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:50.662+0000] {logging_mixin.py:188} INFO - Message from RPA Python1
[2024-02-21T08:17:50.665+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-148.txt')
[2024-02-21T08:17:50.666+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:50.667+0000] {logging_mixin.py:188} INFO - Message from RPA Python2
[2024-02-21T08:17:50.673+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-149.txt')
[2024-02-21T08:17:50.674+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:50.676+0000] {logging_mixin.py:188} INFO - Message from RPA Python3
[2024-02-21T08:17:50.680+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-150.txt')
[2024-02-21T08:17:50.681+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:50.682+0000] {logging_mixin.py:188} INFO - Message from RPA Python4
[2024-02-21T08:17:50.685+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-151.txt')
[2024-02-21T08:17:50.686+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:50.688+0000] {logging_mixin.py:188} INFO - Message from RPA Python5
[2024-02-21T08:17:50.691+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-152.txt')
[2024-02-21T08:17:50.692+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:50.694+0000] {logging_mixin.py:188} INFO - Message from RPA Python6
[2024-02-21T08:17:50.698+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-153.txt')
[2024-02-21T08:17:50.699+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:50.700+0000] {logging_mixin.py:188} INFO - Message from RPA Python7
[2024-02-21T08:17:50.703+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-154.txt')
[2024-02-21T08:17:50.704+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:50.705+0000] {logging_mixin.py:188} INFO - Message from RPA Python8
[2024-02-21T08:17:50.707+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-155.txt')
[2024-02-21T08:17:50.707+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:50.708+0000] {logging_mixin.py:188} INFO - Message from RPA Python9
[2024-02-21T08:17:50.711+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-156.txt')
[2024-02-21T08:17:50.711+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:51.357+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T08:17:51.364+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=extract_email, task_id=get_mail, execution_date=20240124T010000, start_date=20240221T081744, end_date=20240221T081751
[2024-02-21T08:17:51.410+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T08:17:51.426+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
