[2024-02-22T03:53:16.272+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.send_message manual__2024-02-22T03:52:59.030266+00:00 [queued]>
[2024-02-22T03:53:16.278+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.send_message manual__2024-02-22T03:52:59.030266+00:00 [queued]>
[2024-02-22T03:53:16.278+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-22T03:53:16.286+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): send_message> on 2024-02-22 03:52:59.030266+00:00
[2024-02-22T03:53:16.289+0000] {standard_task_runner.py:60} INFO - Started process 416 to run task
[2024-02-22T03:53:16.291+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'send_message', 'manual__2024-02-22T03:52:59.030266+00:00', '--job-id', '309', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmp9014bek1']
[2024-02-22T03:53:16.293+0000] {standard_task_runner.py:88} INFO - Job 309: Subtask send_message
[2024-02-22T03:53:16.321+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.send_message manual__2024-02-22T03:52:59.030266+00:00 [running]> on host e849c64d3231
[2024-02-22T03:53:16.367+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='send_message' AIRFLOW_CTX_EXECUTION_DATE='2024-02-22T03:52:59.030266+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-22T03:52:59.030266+00:00'
[2024-02-22T03:53:17.450+0000] {logging_mixin.py:188} INFO - Đã gửi dữ liệu message 0 tới topic 'credit_card'
[2024-02-22T03:53:17.450+0000] {logging_mixin.py:188} INFO - Lỗi khi gửi dữ liệu tới topic 'credit_card': name 'random' is not defined
[2024-02-22T03:53:17.451+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_email.py", line 61, in produce_to_kafka
    producer.close()
AttributeError: 'cimpl.Producer' object has no attribute 'close'
[2024-02-22T03:53:17.461+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=send_message, execution_date=20240222T035259, start_date=20240222T035316, end_date=20240222T035317
[2024-02-22T03:53:17.472+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 309 for task send_message ('cimpl.Producer' object has no attribute 'close'; 416)
[2024-02-22T03:53:17.506+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-22T03:53:17.518+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
