[2024-02-21T08:06:16.004+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-27T01:00:00+00:00 [queued]>
[2024-02-21T08:06:16.014+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-27T01:00:00+00:00 [queued]>
[2024-02-21T08:06:16.014+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:06:16.023+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-01-27 01:00:00+00:00
[2024-02-21T08:06:16.027+0000] {standard_task_runner.py:60} INFO - Started process 142 to run task
[2024-02-21T08:06:16.029+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-01-27T01:00:00+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmp16gmdt6x']
[2024-02-21T08:06:16.030+0000] {standard_task_runner.py:88} INFO - Job 178: Subtask get_mail
[2024-02-21T08:06:16.061+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-01-27T01:00:00+00:00 [running]> on host 96f19b77385b
[2024-02-21T08:06:16.118+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-27T01:00:00+00:00'
[2024-02-21T08:06:18.608+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_email.py", line 16, in get_mail
    mail.authorize(account=os.getenv("GMAIL_ACCOUNT"), password=os.getenv("GMAIL_PASSWORD"))
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 496, in authorize
    self.authorize_imap(
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 453, in authorize_imap
    self.imap_conn.login(account, password)
  File "/usr/local/lib/python3.8/imaplib.py", line 603, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Too many simultaneous connections. (Failure)'
[2024-02-21T08:06:18.633+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240127T010000, start_date=20240221T080616, end_date=20240221T080618
[2024-02-21T08:06:18.663+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 178 for task get_mail (b'[ALERT] Too many simultaneous connections. (Failure)'; 142)
[2024-02-21T08:06:18.691+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T08:06:18.713+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T08:12:42.947+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-27T01:00:00+00:00 [queued]>
[2024-02-21T08:12:42.957+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-27T01:00:00+00:00 [queued]>
[2024-02-21T08:12:42.957+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:12:42.968+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-01-27 01:00:00+00:00
[2024-02-21T08:12:42.977+0000] {standard_task_runner.py:60} INFO - Started process 132 to run task
[2024-02-21T08:12:42.979+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-01-27T01:00:00+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpf30c11ww']
[2024-02-21T08:12:42.981+0000] {standard_task_runner.py:88} INFO - Job 209: Subtask get_mail
[2024-02-21T08:12:43.016+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-01-27T01:00:00+00:00 [running]> on host 968b17b6b013
[2024-02-21T08:12:43.078+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-27T01:00:00+00:00'
[2024-02-21T08:12:45.581+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_email.py", line 16, in get_mail
    mail.authorize(account=os.getenv("GMAIL_ACCOUNT"), password=os.getenv("GMAIL_PASSWORD"))
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 496, in authorize
    self.authorize_imap(
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 453, in authorize_imap
    self.imap_conn.login(account, password)
  File "/usr/local/lib/python3.8/imaplib.py", line 603, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Too many simultaneous connections. (Failure)'
[2024-02-21T08:12:45.592+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240127T010000, start_date=20240221T081242, end_date=20240221T081245
[2024-02-21T08:12:45.613+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 209 for task get_mail (b'[ALERT] Too many simultaneous connections. (Failure)'; 132)
[2024-02-21T08:12:45.649+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T08:12:45.706+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T08:17:44.323+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-27T01:00:00+00:00 [queued]>
[2024-02-21T08:17:44.332+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-27T01:00:00+00:00 [queued]>
[2024-02-21T08:17:44.333+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:17:44.343+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-01-27 01:00:00+00:00
[2024-02-21T08:17:44.347+0000] {standard_task_runner.py:60} INFO - Started process 81 to run task
[2024-02-21T08:17:44.349+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-01-27T01:00:00+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpvtesl0e7']
[2024-02-21T08:17:44.351+0000] {standard_task_runner.py:88} INFO - Job 241: Subtask get_mail
[2024-02-21T08:17:44.384+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-01-27T01:00:00+00:00 [running]> on host 9f5f399fdbe3
[2024-02-21T08:17:44.453+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-27T01:00:00+00:00'
[2024-02-21T08:17:47.866+0000] {ImapSmtp.py:839} INFO - IMAP search: 'gmail:'Message from RPA Python' after:15-12-2023'
[2024-02-21T08:17:52.071+0000] {logging_mixin.py:188} INFO - Message from RPA Python0
[2024-02-21T08:17:52.075+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-167.txt')
[2024-02-21T08:17:52.076+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:52.077+0000] {logging_mixin.py:188} INFO - Message from RPA Python1
[2024-02-21T08:17:52.081+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-168.txt')
[2024-02-21T08:17:52.081+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:52.082+0000] {logging_mixin.py:188} INFO - Message from RPA Python2
[2024-02-21T08:17:52.086+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-169.txt')
[2024-02-21T08:17:52.086+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:52.087+0000] {logging_mixin.py:188} INFO - Message from RPA Python3
[2024-02-21T08:17:52.091+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-170.txt')
[2024-02-21T08:17:52.092+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:52.093+0000] {logging_mixin.py:188} INFO - Message from RPA Python4
[2024-02-21T08:17:52.096+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-171.txt')
[2024-02-21T08:17:52.097+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:52.098+0000] {logging_mixin.py:188} INFO - Message from RPA Python5
[2024-02-21T08:17:52.101+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-172.txt')
[2024-02-21T08:17:52.102+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:52.103+0000] {logging_mixin.py:188} INFO - Message from RPA Python6
[2024-02-21T08:17:52.106+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-173.txt')
[2024-02-21T08:17:52.107+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:52.108+0000] {logging_mixin.py:188} INFO - Message from RPA Python7
[2024-02-21T08:17:52.111+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-174.txt')
[2024-02-21T08:17:52.111+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:52.112+0000] {logging_mixin.py:188} INFO - Message from RPA Python8
[2024-02-21T08:17:52.114+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-175.txt')
[2024-02-21T08:17:52.115+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:52.115+0000] {logging_mixin.py:188} INFO - Message from RPA Python9
[2024-02-21T08:17:52.118+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-176.txt')
[2024-02-21T08:17:52.118+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:17:52.782+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T08:17:52.793+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=extract_email, task_id=get_mail, execution_date=20240127T010000, start_date=20240221T081744, end_date=20240221T081752
[2024-02-21T08:17:52.827+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T08:17:52.843+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
